# Generated by Django 5.1.5 on 2025-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='priority',
            field=models.CharField(choices=[('m', 'medium'), ('l', 'low'), ('h', 'high')], default='l', max_length=1),
        ),
    ]
