# Generated by Django 5.1.5 on 2025-02-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assigned_to',
            new_name='employees',
        ),
    ]
