# Generated by Django 5.1.5 on 2025-03-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskdetails_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='employees',
        ),
    ]
