# Generated by Django 5.1.5 on 2025-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskdetails_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1),
        ),
    ]
