# Generated by Django 5.1.5 on 2025-01-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='state_date',
            new_name='start_date',
        ),
    ]
