# Generated by Django 5.1.5 on 2025-02-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskdetails_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Low'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tasks.tasks'),
        ),
    ]
