# Generated by Django 5.1.5 on 2025-03-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='employees',
            new_name='assigned_to',
        ),
    ]
