# Generated by Django 5.1.5 on 2025-03-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_delete_employee_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(default='tasks_asset/empty-image.jpg', upload_to='tasks_asset'),
        ),
    ]
